name: Checks

on:
  push:
    branches:
      - master
      - dev-*
      - dev
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/checks.yml"
      - "!.github/workflows/ci.yml"
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: 1.20
      - name: Static Check
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "latest"
          min-go-version: 1.19
          install-go: false
